## Partial Least Sqaures regression

Partial Least Sqaures (PLS) is used when there are many correlated predictor variables and few samples. 

### Example session PLS
```{r use pls package}
library(pls)
```
```{r load datasets}
data("yarn")
data("oliveoil")
data("gasoline")
```

```{r PLSR on gasoline data}
str(gasoline)
gasTrain <- gasoline[1:50,]
gasTest <- gasoline[51:60,]
```
```{r PLSR model (leave-one-out)}
gas1 <- plsr(octane ~ NIR, ncomp = 10, data = gasTrain, validation = "LOO")
summary(gas1)
```
```{r plot RMSEP}
plot(RMSEP(gas1), legendpos="topright")
```
```{r plot ncomp=2}
plot(gas1,ncomp =2, asp = 1, line = T)
plot(gas1, plottype = "scores", comps = 1:3)
```
```{r explained variance}
explvar(gas1)
```
```{r loading plots}
plot(gas1,"loadings", comps=1:2,legendpos="toplef", labels = "numbers", xlab = "nm")
abline(h = 0)
```
```{r predict response values of new observations}
predict(gas1,ncomp = 2, newdata = gasTest)
```
```{r testset RMSEP}
RMSEP(gas1, newdata = gasTest)
```
### Fitting models

```{r models}
str(yarn)
dens1 <- plsr(density ~ NIR, ncomp = 5, data = yarn)
str(oliveoil)
plsr(sensory ~ chemical, data = oliveoil)
olive1 <- plsr(sensory ~ chemical, scale = T, data = oliveoil)
```
### Cross-validation
"CV" = dvides data into segments
"LOO" = leave-one-out

How many components to retain is subjective
```{r example select components}
ncomp.onesigma <- selectNcomp(gas1,method = "onesigma",plot=T)
```

