# Systems Biology Scientific Programming

---
title: "Assignment 2: Multivariate statistics reproducible"
author: "Stijn Hanssen"
date: "Oktober 2018"
output: html_document
---

### Clear working space
```{r}
rm(list=ls())
```

### Set path working directory
```{r}
setwd("C:/Users/stijn/Desktop/Master systems biology/Systems biology year 2/scientific computing/statistic")
```

### Load libraries
```{r}
library(pls)
library(caTools)
```

### Import assay data
```{r}
assayData = read.csv(
  file='AID_624202_datatable.csv',
  header=FALSE, skip=6
)
dim(assayData)
head(assayData,n=5)
qsarData = assayData[,c("V2","V5")]
colnames(qsarData) = c("SID","Score")
dim(qsarData)
head(qsarData,n=5)

```

### Import descriptors file
```{r}
discriptorData = read.csv(
  file='descriptors.csv',
  header=TRUE,row.names = 2
)
dim(discriptorData)
head(discriptorData,n=5)
discriptorData = discriptorData[,-1]
dim(discriptorData)
head(discriptorData,n=5)
```

### Match SID
```{r}
data = qsarData[match(rownames(discriptorData),qsarData$SID),]
data = cbind(discriptorData,data$Score)
dim(data)
head(data,n=5)
#data <- merge(qsarData,discriptorData,by.x = "SID",by.y = 0)
#dim(data)
#data[,]
```
### Data cleaning (remove NA and 0 collumns)
```{r}
data = data[, colSums(is.na(data)) != nrow(data)]
dim(data)
head(data,n=5)

data = Filter(var,data)
dim(data)
head(data,n=5)
```

### Split into train and test data
```{r}
set.seed(101) 
sample = sample.split(data, SplitRatio = .75)
train = subset(data, sample == TRUE)
train_y = train$`data$Score`
test  = subset(data, sample == FALSE)
test_y = test$`data$Score`
```

### pls model 
```{r}
pls_model <- plsr(`data$Score` ~ ., data = train, validation = "LOO")
summary(pls_model)
```


```{r plot RMSEP}
plot(RMSEP(pls_model), legendpos="topright")
```


```{r plot ncomp}

```


```{r loading plots}

```


```{r predict on test set}

```


